name: Security action

on:
  workflow_dispatch: {}
  pull_request:
  push:
    branches:
    - main
    - master
    paths:
    - .github/workflows/semgrep.yml
  schedule:
  # random HH:MM to avoid a load spike on GitHub Actions at 00:00
  - cron: 5 4 * * 6


jobs:
  security-action:
    uses: test-add-more-org/test-reusable-workflow/.github/workflows/semgrep.yml@main
    with:
      repo: ${{ github.repository }}
    secrets:
      SEMGREP_TOKEN: ${{ secrets.GH_SEMGREP_APP_TOKEN }}
