on:
  workflow_dispatch: {}
  pull_request: {}
  pull_request_review: {}
  merge_group: {}
  push:
    branches:
    - main
    - master
  schedule:
  # random HH:MM to avoid a load spike on GitHub Actions at 00:00
  - cron: 33 8 * * *
name: Semgrep
jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-20.04
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: semgrep/semgrep
    steps:
    - uses: actions/checkout@v3
    - run: semgrep ci
